#docker build -t alpine-postgres:3.22 -f Dockerfile-postgres --rm .
ARG ALPINE_VER="3.22"
ARG ALPINE_ARCH="arm64v8"
FROM $ALPINE_ARCH/alpine:$ALPINE_VER
LABEL version="3.22"
ARG TZ="Australia/Brisbane"
ARG DB_DIR="/var/pki"
ARG PG_VER="17"
COPY --chown=root:root --chmod=755 postgres.sh /usr/bin/
RUN apk update && \
    apk upgrade && \
    apk add tzdata alpine-conf coreutils sudo openssl3 gettext-envsubst ca-certificates postgresql$PG_VER && \
    setup-timezone $TZ && \
    mkdir /run/postgresql && \
    sudo chown postgres:postgres /run/postgresql && \
    envsubst '$PG_VER $DB_DIR' < /usr/bin/postgres.sh | tee /usr/bin/postgres.sh
EXPOSE 5432/tcp
VOLUME $DB_DIR
ENTRYPOINT ["postgres.sh"]
