apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-https
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Allow HTTP traffic
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: pki.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 443
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: alpine-nginx:3.22
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: pki-key
          readOnly: true
          mountPath: "/etc/ssl/private/pki.key"
          subPath: "pki.key"
        - name: pki-crt
          readOnly: true
          mountPath: "/etc/ssl/pki.pem"
          subPath: "pki.pem"
        - name: signing-ca
          readOnly: true
          mountPath: "/etc/ssl/signing_ca.pem"
          subPath: "signing_ca.pem"
        - name: root-ca
          readOnly: true
          mountPath: "/etc/ssl/root_ca.pem"
          subPath: "root_ca.pem"
        - name: signing-ca-crt
          readOnly: true
          mountPath: "/etc/ssl/signing_ca.crt"
          subPath: "signing_ca.crt"
        - name: root-ca-crt
          readOnly: true
          mountPath: "/etc/ssl/root_ca.crt"
          subPath: "root_ca.crt"
        - name: root-ca-crl
          readOnly: true
          mountPath: "/etc/ssl/root_ca.crl"
          subPath: "root_ca.crl"
        - name: www
          mountPath: "/var/www/pki"
          readOnly: true
      - name: stunnel
        image: alpine-stunnel-nginx:3.22
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: fpm-key
          readOnly: true
          mountPath: "/etc/ssl/private/fpm.key"
          subPath: "fpm.key"
        - name: fpm-crt
          readOnly: true
          mountPath: "/etc/ssl/fpm.pem"
          subPath: "fpm.pem"
        - name: signing-ca
          readOnly: true
          mountPath: "/etc/ssl/signing_ca.pem"
          subPath: "signing_ca.pem"
        - name: root-ca
          readOnly: true
          mountPath: "/etc/ssl/root_ca.pem"
          subPath: "root_ca.pem"
      volumes:
      - name: pki-key
        secret:
          secretName: pki
          items:
          - key: "tls.key"
            path: "pki.key"
            mode: 0400
      - name: pki-crt
        secret:
          secretName: pki
          items:
          - key: "tls.crt"
            path: "pki.pem"
            mode: 0444
      - name: fpm-key
        secret:
          secretName: fpm
          items:
          - key: "tls.key"
            path: "fpm.key"
            mode: 0400
      - name: fpm-crt
        secret:
          secretName: fpm
          items:
          - key: "tls.crt"
            path: "fpm.pem"
            mode: 0444
      - name: signing-ca
        secret:
          secretName: signing-ca
          items:
          - key: "tls.crt"
            path: "signing_ca.pem"
            mode: 0444
      - name: root-ca
        secret:
          secretName: root-ca
          items:
          - key: "tls.crt"
            path: "root_ca.pem"
            mode: 0444
      - name: root-ca-crt
        configMap:
          name: root-ca-crt
          items:
          - key: "root_ca.der"
            path: "root_ca.crt"
            mode: 0444
      - name: signing-ca-crt
        configMap:
          name: signing-ca-crt
          items:
          - key: "signing_ca.der"
            path: "signing_ca.crt"
            mode: 0444
      - name: root-ca-crl
        configMap:
          name: root-ca-crl
          items:
          - key: "root_ca.crl"
            path: "root_ca.crl"
            mode: 0444
      - name: www
        persistentVolumeClaim:
          claimName: www
---