apiVersion: v1
kind: Service
metadata:
  name: php-fpm
spec:
  clusterIP: None
  selector:
    app: php-fpm
  ports:
  - port: 9001
    targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: alpine-fpm:3.22
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: ca-chain-pem
          mountPath: "/etc/ssl/ca_chain.pem"
          subPath: "ca_chain.pem"
        - name: root-ca
          mountPath: "/etc/ssl/root_ca.pem"
          subPath: "root_ca.pem"
        - name: root-ca-crt
          mountPath: "/etc/ssl/root_ca.der"
          subPath: "root_ca.der"
        - name: signing-ca-pem
          mountPath: "/etc/ssl/signing_ca.pem"
          subPath: "signing_ca.pem"
        - name: signing-ca-key
          mountPath: "/etc/ssl/private/signing_ca.k"
          subPath: "signing_ca.key"
        - name: signing-ca-crt
          mountPath: "/etc/ssl/signing_ca.der"
          subPath: "signing_ca.der"
        - name: www
          mountPath: /var/www/pki
          readOnly: true
      - name: stunnel
        image: alpine-stunnel-fpm:3.22
        imagePullPolicy: Never
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: fpm-key
          mountPath: "/etc/ssl/private/fpm.key"
          subPath: "fpm.key"
        - name: fpm-crt
          mountPath: "/etc/ssl/fpm.pem"
          subPath: "fpm.pem"
        - name: root-ca
          mountPath: "/etc/ssl/root_ca.pem"
          subPath: "root_ca.pem"
      volumes:
      - name: fpm-key
        secret:
          secretName: fpm
          items:
          - key: "tls.key"
            path: "fpm.key"
            mode: 0400
      - name: fpm-crt
        secret:
          secretName: fpm
          items:
          - key: "tls.crt"
            path: "fpm.pem"
            mode: 0444
      - name: root-ca
        secret:
          secretName: root-ca
          items:
          - key: "tls.crt"
            path: "root_ca.pem"
            mode: 0444
      - name: ca-chain-pem
        configMap:
          name: ca-chain-pem
          items:
          - key: "ca_chain.pem"
            path: "ca_chain.pem"
            mode: 0444
      - name: signing-ca-pem
        secret:
          secretName: signing-ca
          items:
          - key: "tls.crt"
            path: "signing_ca.pem"
            mode: 0444
      - name: signing-ca-key
        secret:
          secretName: signing-ca
          items:
          - key: "tls.key"
            path: "signing_ca.key"
            mode: 0400
      - name: signing-ca-crt
        configMap:
          name: signing-ca-crt
          items:
          - key: "signing_ca.der"
            path: "signing_ca.der"
            mode: 0444
      - name: root-ca-crt
        configMap:
          name: root-ca-crt
          items:
          - key: "root_ca.der"
            path: "root_ca.der"
            mode: 0444
      - name: www
        persistentVolumeClaim:
          claimName: www
