<?php
//ASN1 OBJECT CLASSES
const UNIVERSAL_CLASS = 0;
const APPLICATION_CLASS = 1;
const CONTEXT_SPECIFIC_CLASS = 2;
const PRIVATE_CLASS = 3;

//ASN1 UNIVERSAL CLASS TAGS
const BOOLEAN           = 1;
const INTEGER           = 2;
const BIT_STRING         = 3;
const OCTET_STRING       = 4;
const NULL_VALUE        = 5;
const OBJECT_IDENTIFIER = 6;
const OBJECT_DESCRIPTOR = 7;
const EXTERNAL          = 8;
const REAL              = 9;
const ENUMERATED        = 10;
const EMBEDDED_PDV      = 11;
const UTF8_STRING       = 12;
const RELATIVE_OID      = 13;
const TIME_STRING       = 14;
const RESERVED          = 15;
const SEQUENCE          = 16;
const SET               = 17;
const NUMERIC_STRING    = 18;
const PRINTABLE_STRING  = 19;
const T61_STRING        = 20;
const VIDEOTEXT_STRING  = 21;
const IA5_STRING        = 22;
const UTC_TIME          = 23;
const GENERALIZED_TIME  = 24;
const GRAPHIC_STRING    = 25;
const VISIBLE_STRING    = 26;
const GENERAL_STRING    = 27;
const UNIVERSAL_STRING  = 28;
const CHARACTER_STRING  = 29;
const BMP_STRING        = 30;
const DATE              = 31;
const TIME_OF_DAY       = 32;
const DATE_TIME         = 33;
const DURATION          = 34;
const OID_IRI           = 35;
const RELATIVE_OID_IRI  = 36;
